### ISSUE TITLE
Relais Pompe ?

### ISSUE THREAD

**Issue by frouault35** [vieuxsinge/kegwasher#10]
Bonjour à vous!
et tout d'abord merci à vous, je suis sur le point de monter cet engin, et aussi de l'adapter pour aussi laver des fermenteurs. (je pense qu'avec un nouveau mode + des vannes manuelles avec té je peux m'en sortir).
Tout me parait plutôt clair mais j'ai une question concernant l'alimentation de la pompe...
Il semblerait que vous l'alimentiez en 12V à partir de la carte 16 relais du coup ? comme les électrovannes... normal pour une pompe Novax ? ou j'ai du louper quelque chose?
Merci de me répondre si vous passez par là!

**Comment by fredericsureau** [comment]
Salut à toi,

La carte 16 relais est bien alimentée en 12VDC pour faire fonctionner les relais.
La pompe Novax est alimentée en 230VAC, le relais fait seulement la coupure (et c'est le même principe pour les électrovannes même si elles sont reliées à la même alim 12VDC que la carte relais)

Je t'invite à regarder le fonctionnement des relais avant le montage électrique, histoire d'éviter de cramer des composants ;)

Bon courage pour le montage
Fred

**Comment by frouault35** [comment]
Ah je comprends mieux ;) , je pensais pas qu'on pouvait lui faire passer du 230v, sans justement la faire cramer, je vais regarder la doc des cartes relais, ca serait dommage de tout bruler !
En tout cas Merci pour le partage, vous gérez! on mettra une petite photo quand on aura fini!
