### ISSUE TITLE
Relai Pompe

### ISSUE THREAD

**Issue by blurp1478963** [vieuxsinge/kegwasher#7]
Bonjour,

En étudiant un peu le cablage sur les photos, je ne vois pas de relai pour la pompe, est-elle directement branchée en 220 sur la carte relai ?

Merci!

**Comment by sjavierdu** [comment]
Hi, the relay support máx: 10A/250VAC, 10A/30VDC, I think is enough for the pump. 
but yes, I edit my message, I saw a second relay for the pump

**Comment by sjavierdu** [comment]
I think channel 9 of the relay is not used for the pump and is replaced by an ssr relay, but @fredericsureau say in other hand that he buy a 16 channel relay for this. 

look! this video show as how to add a second contactor (in our case relay) in your relay optocoupler. I believe it not the case: https://www.youtube.com/watch?v=wGYn83sksgE&t=564s
Maybe it helps a little, I didn't know the second ssr relay, I don't see it in the material list (maybe it's a change on the go, )

merci!
merci!

**Comment by fredericsureau** [comment]
Oui c'est bien le relai n°9 qui est utilisé directement pour activer la pompe.
Les relais supportent 220VAC/10A ce qui est suffisant pour une petite pompe comme la Novax.

En regardant sur la photo, tu vois un cable marron qui court le long de la carte des relais sur la gauche.
C'est le fil de phase de la pompe.

Bon courage !

**Comment by fredericsureau** [comment]
@sjavierdu The SSR relay is used for the heating element. The pump is directly actionned by the relay n° 9.

**Comment by blurp1478963** [comment]
Merci! Nous avons presque fini notre laveuse! Nous avons qq input à filer pour contribuer dès qu'elle sera en marche!
